### ISSUE TITLE
Has this been published already?

### ISSUE THREAD

**Issue by psygo** [StinsonZhao/obsidian-plugin-goban-sgf#1]
I'm trying to find this on Obsidian's Community Plugins but I can't seem to find it. Has it been published already? Were there any issues?

Also, on a sidenote, as a suggestion, I think it would also be nice to have a section on `README.md` for references to other similar projects. For example:

- [@barollet/obsidian-goban](https://github.com/barollet/obsidian-goban)
    - This is also probably the simplest template possible for this kind of thing, although it has way less features than this one.
- [@THeK3nger/obsidian-goban](https://github.com/THeK3nger/obsidian-goban)

**Comment by qcgm1978** [comment]
It seems that you have to clone the project and link it to the plugins folder of downloaded Obsidian app.

**Comment by StinsonZhao** [comment]
Finally released, you can now find it in the Obsidian community plugin list.
