### ISSUE TITLE
Use this code to create a minimal template for embedding Sabaki and its Game Graph on a webpage?

### ISSUE THREAD

**Issue by psygo** [StinsonZhao/obsidian-plugin-goban-sgf#2]
Thanks for your outstanding work with the Sabaki project.

I've been wanting to use Sabaki/Shudan on a webpage for a long time, but the Preact setup plus the fact that the Game Graph isn't on a separate package made it too complicated for me.

Would you be willing to help with creating a minimal template for using Sabaki/Shudan with the Game Tree/Graph on a webpage? (I'm open to DMs as well...)

**Comment by StinsonZhao** [comment]
I understand your requirements, but if it's just a web version of Sabaki, I believe this should be a matter for the Sabaki team to consider.

Whether it's the Sabaki application or the plugins I am currently developing, the game record data is local. Moving it to a web platform would require storing the data online, which I believe is the biggest change. This would also lead to a series of cost issues, so a web version may not be the best choice.
